Add basic deployment of code-submitter
srobo/ansible pull request #30
Opened 2023-01-21 18:48 UTC by RealOrangeOne

## Summary

Fixes https://github.com/srobo/infrastructure-team-minutes/issues/23

Add a deployment for the code-submitter to Ansible.

The code submitter runs as `www-data`, and is installed as this user.

## Code review

### Testing

- [x] applied the configuration locally
- [ ] manually validated the new behaviour

### Links

This converts https://github.com/srobo/server-puppet/blob/master/modules/www/manifests/code_submitter.pp to ansible.

2023-01-21 20:37 UTC, PeterJCLaw commented
Related: https://github.com/srobo/tasks/issues/971 (maybe fixes?)

2023-01-23 09:25 UTC, RealOrangeOne commented
It doesn't _directly_ fix, as that task is also about _deploying_ it, rather than simply having the _ability to_ deploy it, but worth keeping track of nonetheless.

2023-01-28 17:02 UTC, RealOrangeOne commented on roles/competitor-services-nginx/templates/nginx.conf
> +    include /etc/nginx/sites-enabled/*;
This feels like a hack. By default, nginx expects a `site` to be a `server` block. We however want it to be a `location` block.

2023-01-28 18:01 UTC, PeterJCLaw reviewed
Nice, this looks like a great start.

Bunch of suggestions for improvements, the main blocker being that the validation of the partial nginx config means this doesn't actually work right now.

2023-01-28 18:01 UTC, PeterJCLaw commented on group_vars/all.yml
> -certbot_create_if_missing: true
Why is this setting being removed? We do definitely want certbot to create missing certs.

2023-02-01 19:39 UTC, RealOrangeOne commented on roles/competitor-services-nginx/templates/nginx.conf
> +    include /etc/nginx/sites-enabled/*;
> `locations-enabled`

I like this

2023-02-01 19:42 UTC, RealOrangeOne commented on host_vars/monty.studentrobotics.org.yml
> -add_hsts_header: true
It's a scope change. Changing the default and stopping it being overridden for each host.

2023-02-01 19:44 UTC, RealOrangeOne commented on playbook.yml
> +    - code_submitter
Ansible standardizes on using `_` as the delimiter https://ansible-lint.readthedocs.io/rules/role-name/.

I agree though it should be changed to be consistent. If we want to follow the standard we can deal with that later.

2023-02-01 19:45 UTC, RealOrangeOne commented on roles/code_submitter/templates/code-submitter.service
> +ExecStart={{ venv_dir }}/bin/uvicorn code_submitter.server:app --uds /var/run/code-submitter/code-submitter.socket --forwarded-allow-ips='*' --root-path /code-submitter
Puling the value into nginx _might_ be possible, but highly unlikely. Hardcoding is probably best here.

2023-02-01 19:47 UTC, RealOrangeOne commented on roles/code_submitter/templates/nginx.conf
> +# Changing this url? Also update the auth url used by the code_submitter
This was copied from the previous configuration, I couldn't immediately see what it meant either.

2023-02-01 19:48 UTC, RealOrangeOne commented on roles/competitor-services-nginx/templates/nginx.conf
> +worker_processes      1;
Correct, the basics of the config are identical. The only changes are in the final `server` block.

2023-02-01 20:04 UTC, RealOrangeOne commented on roles/code_submitter/tasks/main.yml
> +    validate: /usr/sbin/nginx -t -c %s
I see the issue. We're validating just the include file, rather than the entire config

2023-02-01 20:05 UTC, PeterJCLaw commented on .ansible-lint
> +  - no-handler
What are you meant to use instead? Does it make sense for us to use that instead?

2023-02-01 20:07 UTC, PeterJCLaw commented on group_vars/all.yml
> -certbot_create_if_missing: true
I think we do want this in development too? Since we do want to be able to validate TLS locally? I can't recall exactly how that was working, but I had thought it _was_ working. Either way, this PR doesn't feel like the place to be changing this.

2023-02-02 17:15 UTC, RealOrangeOne commented on .ansible-lint
> +  - no-handler
It'd be to use a handler, which we're using for things like "restart nginx". Using it here for running migrations would work, it just felt like a bit of the wrong abstraction for our use case here.

2023-02-04 11:46 UTC, PeterJCLaw commented on host_vars/monty.studentrobotics.org.yml
> -add_hsts_header: true
I feel like this is something which we do want to be setting at host level though, or at least overriding at that level. Note that we do set this currently for the local proxy machine (I was wrong in my previous comments about setting up TLS on locally deployed machines).

Either way if we do want to make this change, please could it be hoisted to a separate PR so that it can be considered on its own merits.

2023-02-04 14:39 UTC, PeterJCLaw commented on roles/code_submitter/templates/nginx.conf
> +# Changing this url? Also update the auth url used by the code_submitter
Looking in the history it seems like this was originally attached to the `nemesis` (userman) deployment, back when the code submitter was used with per-user logins. For some reason it got erroneously moved, likely after we moved away from that approach. I suggest just dropping this.

2023-02-04 14:42 UTC, PeterJCLaw commented on group_vars/all.yml
> -certbot_create_if_missing: true
Scratch that, we do disable this in local environments. However the value in the original package defaults to `false`, which would leave a production instance without a certificate if we missed this. I suspect that's why I flipped the default -- so that production is right by default and local instances override it. That feels like it's probably the way around we want.

Either way if you feel that this should change, please break it out into a separate PR so it can be discussed on its own merits.

2023-02-04 14:44 UTC, PeterJCLaw commented on Vagrantfile
> +      "competitor_svcs" => ["sr-compsvc"],
:lady_beetle: This group name does not match the one in the `hosts` file.

2023-02-05 14:02 UTC, PeterJCLaw commented on .ansible-lint
> +  - no-handler
Ah, ok. Yeah, for the case of rebuilding the venv the `when` approach does feel a bit more natural. Can we tag it inline though, perhaps with an explanation of why we think the exception is worthwhile?

2023-02-05 14:03 UTC, PeterJCLaw commented
@RealOrangeOne I think this is generally fine, however see various comments which need resolving before we should merge.

2023-02-05 14:03 UTC, PeterJCLaw commented
I thiiink they're mostly simple fixes, but if any of the conversations would be quicker to address with a quick call let's do that.

2023-02-07 20:35 UTC, PeterJCLaw requested changes

2023-02-07 20:35 UTC, PeterJCLaw commented on group_vars/all.yml
> +certbot_create_if_missing: true
Please can we undo the diff here if nothing's meant to be changing (note also that these were previously alphabetically listed, fixing that should resolve the diff noise).

2023-02-07 20:35 UTC, PeterJCLaw commented on host_vars/monty.studentrobotics.org.yml
> -certbot_create_if_missing: true
I think this still needs restoring?

2023-02-07 20:35 UTC, PeterJCLaw commented on roles/secrets/tasks/main.yml
> +    mode: "0700"
:lady_beetle: Unfortunately `0700` means that no-one can read the content of this directory, even the service accounts which are meant to be able to read things. I think we probably want this to be `0711` (i.e: `a+x`) so that everyone can access files within the directory that they're entitled to read, while still preventing enumeration of the directory (which `+r` would grant).

Without this, the service currently fails to start for me. (How was it working for you?)

Alternatively we might be able to do some shenanigans with systemd granting rights or something, but this seems simpler.

2023-02-08 21:24 UTC, RealOrangeOne commented on host_vars/monty.studentrobotics.org.yml
> -certbot_create_if_missing: true
It's defined in `group_vars/all.yml` so it won't be needed here.

2023-02-08 22:28 UTC, PeterJCLaw approved these changes

2023-02-12 19:54 UTC, merged